gazebo_ros_control:
  pid_gains:
    front_left_wheel: {p: 1.0, i: 0.1, d: 0.0}
    front_right_wheel: {p: 1.0, i: 0.1, d: 0.0}
    rear_left_wheel: {p: 1.0, i: 0.1, d: 0.0}
    rear_right_wheel: {p: 1.0, i: 0.1, d: 0.0}
    iiwa_joint_1:  {p: 800.0, i: 100, d: 80.0}
    iiwa_joint_2:  {p: 800.0, i: 1000, d: 100.0}
    iiwa_joint_3:  {p: 800.0, i: 10, d: 5.0}
    iiwa_joint_4:  {p: 800.0, i: 10, d: 80.0}
    iiwa_joint_5:  {p: 300.0, i: 5, d: 10.0}
    iiwa_joint_6:  {p: 50.0, i: 1, d: 1.0}
    iiwa_joint_7:  {p: 10.0, i: 0.1, d: 1.0}
#    iiwa_joint_1:  {p: 700,  i: 0.01, d: 100}
#    iiwa_joint_2:  {p: 10000,  i: 100, d: 100}
#    iiwa_joint_3: {p: 4500,  i: 35, d: 1}
#    iiwa_joint_4:  {p: 5500,  i: 60, d: 2}
#    iiwa_joint_5: {p: 1000,  i: 30, d: 0.01}
#    iiwa_joint_6:  {p: 500,  i: 0.1, d: 0.01}
#    iiwa_joint_7:  {p: 100,  i: 0.1, d: 0.01}

